### ISSUE TITLE
Create resource to Deploy Default StateStore

### ISSUE THREAD

**Issue by s8sg** [s8sg/faas-flow#103]
1> Decide on default statestore
2> Create resource to deploy in K8s and Swarm
3> Change `FaasFlow` to use default store, if not defined

**Comment by vtolstov** [comment]
May be you can use memory store that uses nats to sync across all instances?

пт, 23 авг. 2019 г., 9:22 Swarvanu Sengupta <notifications@github.com>:

**Comment by s8sg** [comment]
Which memory store uses nats to sync across all instances ? 
We need strong consistency, is it possible with such system ?

**Comment by vtolstov** [comment]
If this is not for tests and need strongly consistent, I'm recommend etcd. It already stable and used by k8s.

**Comment by s8sg** [comment]
Yeah I was also considering `etcd`

**Comment by s8sg** [comment]
I think its good that we Provide default statestore in SDK, maybe in memory one. For faasflow template I may use the etcd as default and initialize it, user may override it if needed.

**Comment by s8sg** [comment]
[Faas-Flow Infra](https://github.com/s8sg/faas-flow-infra) is created, which includes the Kubernets and Docker swarm resource to deploy the StateStore, DataStore and Jaeger for tracing
