### ISSUE TITLE
add additional fields to EventHandler NodeStart/NodeEnd

### ISSUE THREAD

**Issue by vtolstov** [s8sg/faas-flow#110]
to get ability to known what the root node in event handler we need to have index of node.
so if index equal 1 we known that this is root node in dag or subdag.
Now to get this info i need to parse nodeId inside event handler.

**Comment by vtolstov** [comment]
and may be some link to state and store keys? i can extract this data based on nodeId... but may be this is can be useful?

**Comment by vtolstov** [comment]
@s8sg what is the best way to pass additional data to event handler like node index?
I can modify signature of event functions, or pass to event handler sdk.Dag and get from it needed data based on node if?

**Comment by s8sg** [comment]
@vtolstov I would recommend to take the `sdk` changes in low priority. We have the `sdk` into a stage where it doesn't need any major changes in terms of feature but stability
