### ISSUE TITLE
Error failed to init tracer

### ISSUE THREAD

**Issue by Qolzam** [s8sg/faas-flow#114]
I followed [faas-flow README](https://github.com/s8sg/faas-flow#getting-started) but I got error : 

`echo "Adam" | faas invoke greet
[ Failed ] failed to init request tracer, error failed to init tracer, error lookup jaegertracing on 10.96.0.10:53: server misbehaving` 

I have ` enable_tracing: false` in faas-flow environment. But seems `faas-flow` trying to initialize  jaeger tracing! Is it a normal behavior?

**Comment by s8sg** [comment]
@Qolzam Thank you for reporting this. Once you set `enable_tracing: false`, it must not try to initialize jaeger. Let me check

**Comment by s8sg** [comment]
Before we initialize, we should check if monitoring is enabled
https://github.com/s8sg/faas-flow/blob/72996359a4082cc2085dd440f7cee7f7a5b9baff/template/faas-flow/handler.go#L275
This is the function
https://github.com/s8sg/faas-flow/blob/72996359a4082cc2085dd440f7cee7f7a5b9baff/template/faas-flow/handler.go#L223
None of the `Executor` code checks the function. I'll fix this

**Comment by Qolzam** [comment]
Thank you @s8sg for fast checking. Is there any way work around? I have tried to comment  that part (temporary) in template file but I got another error:

`Server returned unexpected status code: 504 - `

function logs show :

```
2019/10/01 10:41:56 stdout: [Request `bm9iqt2rpglpl55op9ng`] Created

2019/10/01 10:41:56 stderr: 2019/10/01 10:41:56 Warning: using default StateStore, distributed async call will not work properly

2019/10/01 10:41:56 stdout: [Request `bm9iqt2rpglpl55op9ng`] DAG state initiated at StateStore
[Request `bm9iqt2rpglpl55op9ng`] Executing node 0_1_sync

2019/10/01 10:41:56 stdout: [Request `bm9iqt2rpglpl55op9ng`] Executing modifier
[Request `bm9iqt2rpglpl55op9ng`] Completed execution of Node 0_1_sync
[Request `bm9iqt2rpglpl55op9ng`] Completed successfully

2019/10/01 10:42:06 Upstream HTTP request error: Post http://127.0.0.1:8082/: context deadline exceeded
2019/10/01 10:42:06 Upstream HTTP killed due to exec_timeout: 10s
```

**Comment by s8sg** [comment]
This is due to last commit. We were initialising an unbuffered channel for exit. Please try again with the latest code.

**Comment by Qolzam** [comment]
Thank you @s8sg for fix. However I got `Gateway Timeout` in response.

Here is the function log: 
```
2019/10/04 06:46:35 Started logging stderr from function.
2019/10/04 06:46:35 Started logging stdout from function.
2019/10/04 06:46:35 OperationalMode: http
2019/10/04 06:46:35 Writing lock-file to: /tmp/.lock
2019/10/04 06:46:35 Metrics server. Port: 8081
2019/10/04 06:46:35 stderr: 2019/10/04 06:46:35 Flow using file based default StateStore, distributed dag request will fail if function replication factor > 1

2019/10/04 06:53:16 stdout: [Request `bmbeon6hsshqj9r6efdg`] Created

2019/10/04 06:53:16 stderr: 2019/10/04 06:53:16 Warning: using default StateStore, distributed async call will not work properly

2019/10/04 06:53:16 stdout: [Request `bmbeon6hsshqj9r6efdg`] DAG state initiated at StateStore
[Request `bmbeon6hsshqj9r6efdg`] Executing node 0_1_sync

2019/10/04 06:53:16 stdout: [Request `bmbeon6hsshqj9r6efdg`] Executing modifier
[Request `bmbeon6hsshqj9r6efdg`] Completed execution of Node 0_1_sync
[Request `bmbeon6hsshqj9r6efdg`] Completed successfully

2019/10/04 06:53:26 Upstream HTTP request error: Post http://127.0.0.1:8082/: context deadline exceeded
2019/10/04 06:53:26 Upstream HTTP killed due to exec_timeout: 10s
```

**Comment by s8sg** [comment]
This is due to the vendor was not updated in the template 😞

**Comment by s8sg** [comment]
@Qolzam Can you please give it another try and reopen if necessary

**Comment by Qolzam** [comment]
Thank you @s8sg for fix. I checked and it worked. I will dig more on your great job :)
