### ISSUE TITLE
data store interface

### ISSUE THREAD

**Issue by vtolstov** [s8sg/faas-flow#122]
I'm not cleanup data store when execution finishes. For example for debug or historical data.
I need to have ability to easy get data from data store via passing requestID and Vertex name.

Now key looks like 0_3_unistack_cms_account.AccountService.AccountCreate--0_7_unistack_cms_project.ProjectService.ProjectCreate

So without knowledge about key format is impossible to externally get this data. Yes, i can write own data store, that store needed key, and get data directly from backend. But why not add this ability to data store interface? Something like Lookup(requestID string, Node(or Vertex) string) ?

**Comment by s8sg** [comment]
So if I understand correctly, you are asking to get a way to find the intermediate data between two nodes. So currently the design is:
```sh
<from_node>-<to_node>
```

`LookUp()` as I understand is something that can retrieve the data given a request ID and from and to vertex. Now is it necessarily need to be added in the data store and the interface is the question

The interface is designed for keeping the consumer in mind, but not a generic one which applies to all consumer. Here the primary consumer for a `DataStore` is the workflow excutor. And the `StateStore` interface is enough for it now.

**Comment by s8sg** [comment]
If you need the `LookUp` functionality, best to write a separate module. We can expose the generation of code logic in sdk 
https://github.com/s8sg/faas-flow/blob/master/sdk/executor/executor.go#L894

**Comment by vtolstov** [comment]
main problem that after execution completes i can get this data?
So for example i have dag stored somewhere, i can load it, validate, and get this data back.
But if that dag changed? For example i have stored data in db or in some kv. After some time dag is changed, for example added new node. In this case i can't determine older run data.
Does it possible to create one solution to both cases?
Does node name is unique across dag? So my use-case able to get data also in case of dag is changed after data is written

**Comment by s8sg** [comment]
DAG are final in nature, there supposed two be no changes in a DAG where there is an active execution

**Comment by vtolstov** [comment]
I need only read only access, not write. So this will not break anything from running dag execution

**Comment by s8sg** [comment]
The idiomatic way of doing it will be to create wrapper on top of the state-store and ignore the cleanup call. Then you can add a separate library that fetch the data based on the key generated with the node name. There is no changes that is needed in SDK now
