### ISSUE TITLE
add ability to access state info for current dag node and data store from operation

### ISSUE THREAD

**Issue by vtolstov** [s8sg/faas-flow#123]
example use-case - restarting workflow, when some dag nodes with operations completed successful.
So if user wants, he can access state store and query current dag node state (if user runs the flow with the same request id as before) and also state to allow read/write to data store.

**Comment by s8sg** [comment]
@vtolstov I would recommend to take the `sdk` changes in low priority. We have the `sdk` into a stage where it doesn't need any major changes in terms of feature but stability.

**Comment by vtolstov** [comment]
main problem now, that then dag execution failed i can't easy recreate recovery dag because failure handler can receive only error message without knowledge which node failed.
Operation can't access state and data storage so it don't known about previous state.
