### ISSUE TITLE
add CutDag(id string) and Reverse() sdk.Dag funcs

### ISSUE THREAD

**Issue by vtolstov** [s8sg/faas-flow#124]
I want to add two funcs to sdk.Dag
* CutDag(id string) (*Dag, error)
    it returns part of dag starting from specified node, or error if node not found
* Reverse() (*Dag, error)
    it return reverse dag

I'm use it in my workflow.
CutDag is used when part of workflow failed. I can start dag execution from specific place without re-run all operations
Reverse is used when workflow failed, EventHandler have nodeId of failed operation, so i can easy recreate recovery/compensate Dag and schedule it to start.

I'm don't test it tightly with branching now and subdags, but i think that it must works in this case too. As it operates on sdk.Dag primitives.

**Comment by vtolstov** [comment]
@s8sg please check #125 does it looks right or i'm miss something?

**Comment by s8sg** [comment]
@vtolstov How do you handle a case where a branch has made before the cut and merges with the dag after the cut ?

**Comment by vtolstov** [comment]
If parent of node placed before cut, child goes as started node.
So this is human decision where to cut

**Comment by vtolstov** [comment]
@s8sg i think that for feature improvements i can add detection. So if after cut in dag present aggregation of different branches that started before cut or multiple branches present after cut, that have parents before - forbid this cut and return errors.

**Comment by s8sg** [comment]
> CutDag is used when part of workflow failed. I can start dag execution from specific place without re-run all operations.  
  
A workflow failure is a failure of the workflow as a whole; there is already pause and start. I don't see a need for it now 

> So this is human decision where to cut

The DAG execution is bound with some laws, for every dag execution there is only one start node and only one end node. This is decided as a DAG for a reason.

**Comment by s8sg** [comment]
As I mentioned before I'm no willing to add any more feature on the SDK. We have use cases on the faasflow itself, which we need to focus now. For now I'll close all the issue which are not in priority in `sdk` and revisit when we have dealt with the stability and ease of use for the product itself.
