### ISSUE TITLE
Implement StateStore on 3rd party KV Store - consul, etcd

### ISSUE THREAD

**Issue by s8sg** [s8sg/faas-flow#14]
Execution state currently being forwarded as a data for the next phase. This will work well until the pipeline is less complicated than a chain of function. For a more complicated example such as `dag`, we need to have a secondary KV store to manage the execution state. A `ExecutionState` manager can be `ZooKeeper` or `Consul`

**Comment by alexellis** [comment]
ZooKeeper is heavy-weight - have you considered using something like NATS, BoltDB, Minio or etcd (etcd is often packaged with K8s btw)

**Comment by s8sg** [comment]
`etcd` can be a good option. I'm not familiar of using other as a `KV` store. I'll give them all a try. I just made one with consul [faas-flow-consul-statestore](https://github.com/s8sg/faas-flow-consul-statestore)

**Comment by s8sg** [comment]
`etcd` StateStore is implemented as: [faas-flow-etcd-statestore](https://github.com/s8sg/faas-flow-etcd-statestore)
