### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by tim64195419** [s8sg/faas-flow#143]
command: "faas-cli build -f test-flow.yml" with the example
I got build error 

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/14270024/122675097-80f55600-d20a-11eb-95e1-f2bacc6bf29b.png">

I can't understand what is going wrong?

**Comment by dimgiagos44** [comment]
probably your handler.go fails to compile due to a syntax error for example..

**Comment by TYsonHe** [comment]
go's format is wrong
