### ISSUE TITLE
Docker images problem

### ISSUE THREAD

**Issue by Siziyou** [s8sg/faas-flow#153]
In the dockerfile of template,I found that of-watchdog can't be pulled with "openfaas/of-watchdog" directly, which leads to docker.io/openfaas/of-watchdog.
However,I found it in ghcr.io/openfaas/of-watchdog.
Maybe the old repository has been moved to ghcr.io?Shall I modify the dockerfile?

**Comment by Siziyou** [comment]
I have modified the dockerfile to solve the problem.

**Comment by s8sg** [comment]
Can you please raise an MR to fix it

**Comment by Siziyou** [comment]
pleasure :>,but I'm not sure whether it is right because there's no version 0.7.7 anymore in ghcr.io.
