### ISSUE TITLE
http read panic

### ISSUE THREAD

**Issue by chennqqi** [s8sg/faas-flow#43]
https://github.com/s8sg/faas-flow/blob/86030be291e1fde88420b27fba186fa0da18ec46/template/faas-flow/handler.go#L509

This line has a bug?
```
	client := &http.Client{}
	res, resErr := client.Do(httpreq)
	resdata, _ := ioutil.ReadAll(res.Body)
	if resErr != nil {
		return resdata, resErr
	}
```
  if resErr was not nil, ioutil.ReadAll(res.Body) will cause a painic

**Comment by s8sg** [comment]
Good catch. Can you please create a PR fixing it

**Comment by s8sg** [comment]
I reopened, closed by mistake

**Comment by chennqqi** [comment]
I created a pull request to fix this issue

**Comment by s8sg** [comment]
Merged
