### ISSUE TITLE
remove enviroment variable `workflow_name`

### ISSUE THREAD

**Issue by chennqqi** [s8sg/faas-flow#68]
currently `workflow_name` must equal to function name, maybe we can get it from
```
workflow_name1 := strings.Split(os.Getenv("Http_Host"), ".")[0]
```

**Comment by s8sg** [comment]
I like this one

**Comment by s8sg** [comment]
@chennqqi we need to check and find a logic so that it works accross all deployments

**Comment by chennqqi** [comment]
an other way:
`docker exec`  an  faas function docker 
ENV|grep $functionname
There is an other way:
   strings.Split(os.Getenv("HOSTNAME"), "-")[0] if flow name dosen't contains `-`

https://github.com/openfaas/workshop/blob/master/lab4.md#inject-configuration-through-environmental-variables

**Comment by chennqqi** [comment]
already test of-watchdog

**Comment by s8sg** [comment]
@chennqqi Which one works with `of-watchdog`
```
workflow_name1 := strings.Split(os.Getenv("Http_Host"), ".")[0]
```
or
```
strings.Split(os.Getenv("HOSTNAME"), "-")[0]
```
And it needs to work on swarm, kubernets and other deployment

**Comment by s8sg** [comment]
For docker swarm, none of the above approaches works. Till we have a solution which is agnostic of the deployment, we have to wait.

**Comment by s8sg** [comment]
As we are using `of-watchdog` we have the `Request.Host`, for a function `myfunc` the Host is either 
```
myfunc:8080 // swarm
myfunc.openfaas-fn:8080 // k8s
```
we can use a simple regex to parse the function name, as such 
```regex
^[^:.]+\s*
```
This matches all character till occurrence of `:` or `.`. As OpenFaaS function doesn't let user use either of then in function name, this should work well

**Comment by s8sg** [comment]
This is merged.
