### ISSUE TITLE
Typo in Image

### ISSUE THREAD

**Issue by kwojcicki** [s8sg/faas-flow#71]
https://github.com/s8sg/faas-flow/raw/master/doc/overview.jpg 

Async Chian should be Async Chain :)

**Comment by s8sg** [comment]
thank you for pointing it, will fix that.

**Comment by kwojcicki** [comment]
Seems it was fixed as part of https://github.com/s8sg/faas-flow/commit/de0012459789bb9f57aa7b82d02082fdd1327c35 :)
