### ISSUE TITLE
Add timeout option for operations

### ISSUE THREAD

**Issue by s8sg** [s8sg/faas-flow#74]
When performing a Operation, user can mention a timeout. This timeout will be applied for each operation types. If timeout happen, operation will be killed and execution will be failed as if the operation has failed. If operation retry is configured, it will be retried.

**Comment by vtolstov** [comment]
What you think about global timeout for workflow?
So each operation have timeout and full workflow operations can have timeout too. Because if you have retries timeout for operation work for retry operation , but if i want to have global timeout for full workflow this is hard to do..

**Comment by s8sg** [comment]
Duplicate #73
