### ISSUE TITLE
Function cannot be called if gateway is not in the same namespace

### ISSUE THREAD

**Issue by tim-hellhake** [s8sg/faas-flow#77]
Since https://github.com/s8sg/faas-flow/pull/67 the function is called through the gateway.
This works only if the gateway is in the same namespace as the function.
As you can see [here](https://docs.openfaas.com/deployment/kubernetes/) the recommended way is to place the functions in a separate namespace.

**Comment by s8sg** [comment]
Thank you for the issue and PR. In docker swarm with the namespace the request will fail, so I cross checked OpenFaaS cloud for reference for the default, it seems there is no default. In that case gateway is not set it’s likely to fail. I guess having the default with the namespace is better. I’ve merged the PR.
