### ISSUE TITLE
go.mod

### ISSUE THREAD

**Issue by vtolstov** [s8sg/faas-flow#85]
thanks for you many pr's, can you remove vendor and add go.mod ?
as of go 1.11 it supported and very useful. also repo does not needs to be have external deps.

**Comment by s8sg** [comment]
Sounds good. I'm a bit overwhelmed by all the pending issues now. I'll gladly take a PR 😄

**Comment by chennqqi** [comment]
openfaas not support go.mod now, i think remove vendor is not a good idea

**Comment by s8sg** [comment]
Thats a good point, although we are using our own `Dockerfile` and template. 
I'm not very aware on `go.dep`, what is the behaviour is user include `vendor` for dependency. Does vendor get prioritised ?

**Comment by vtolstov** [comment]
we can add go.mod file and also run when update deps go mod vendor. so we have in repo vendor folder, but it used only when building without go.mod support.
For others it will be ignored by go tool and it fetches deps based on go.mod file.

**Comment by s8sg** [comment]
This is not an `sdk` enhancement issue
