### ISSUE TITLE
close method for store

### ISSUE THREAD

**Issue by vtolstov** [s8sg/faas-flow#86]
my toy store needs to be closed at the end of work, does i need to put close to Cleanup method or we need something new for closing store?

**Comment by s8sg** [comment]
I think `cleanup()` is the last call made to the `Stores` and only called once in an execution lifetime. You can perform `close()` there.  For each workflow request `Init()` and `cleanup()` called only once.  
  
Alternatively you can open a connection at workflow server initialisation if your workflow repeatedly take connection. you may keep the connection open() till you shutdown the server. It will save some time.

**Comment by vtolstov** [comment]
thanks! i'm init connection in init and close on cleanup

**Comment by vtolstov** [comment]
I think that we still need some open and close methods for store. Simple example:
i'm create executor that works with local file as db. So it opens it in exclusive lock.
Executor
I'm pass to executor two requests. If i'm close db/file on cleanup i need to reopen it in Init or Configure. But i need it init only when define executor....
Or create some additional checks and open db only once.
May be best to provide close method for interface that close handler? Cleanup delete all stuff, and close try to close connection or fd?

**Comment by s8sg** [comment]
```go
	// Configure the DaraStore with flow name and request ID
	Configure(flowName string, requestId string)
	// Initialize the DataStore (called only once in a request span)
	Init() error
	// Cleanup all the resorces in DataStore
	Cleanup() error
```
None of these method are meant to handle open/close on database. The open and close must be explicitly handled. Its not the executor concern to close a DB connection, neither it can determine the most optimal way to manage a connection. You can create a DB connection before Execute() call and close it after. Or you may keep it open for the entire time you are executing one or more request. Init is here to initialize requests specific resources in DB. Like creating bucket, not to initialize connection. Similarly Cleanup() is to delete request resources form DB, not to close() connection. I hope that helps

**Comment by vtolstov** [comment]
ok
