### ISSUE TITLE
Add ability to stop/pause/resume an workflow

### ISSUE THREAD

**Issue by s8sg** [s8sg/faas-flow#88]
As suggested in issue-#81 by @kwojcicki 
We will provide ability to stop a workflow

**Comment by vtolstov** [comment]
does also we need to pause workflow or only stop?

**Comment by s8sg** [comment]
Pause would be good to have. Implementing pause will need some changes in executor.     

Stop will be a implicit feature of the sdk. It can use the statestore to mark a pipeline as inactive. If a node is already started execution of its operations then it will be hard to stop, but afterwards the execution will be stopped.   
   
pause may need to be handled by the executor. Currently we forward the intermediate state to next execution via http request. While it pause the intermediate state needs to be stored somewhere so that it can be replayed.  While executing a branches all intermediate request need to be stored. We can use state store for it. Again it would be hard to pause an active Node execution  but next nodes can be paused

**Comment by vtolstov** [comment]
How can i serialize current workflow to store? Does it already have some sort of ability to export it to some representation?

**Comment by s8sg** [comment]
Check https://godoc.org/github.com/s8sg/faas-flow/sdk/exporter

These provide functionality to export the workflow definition in JSON

**Comment by vtolstov** [comment]
Thanks! really helpful. How can i after that import flow by this json representation?

**Comment by vtolstov** [comment]
as i see now is only way it to unmarshal json to https://godoc.org/github.com/s8sg/faas-flow/sdk#DagExporter after that iterate over nodes and construct DAG. Do you have some different way of restoring workflow from json?

**Comment by s8sg** [comment]
Now I see whats your point, no thats the only way for now.

**Comment by vtolstov** [comment]
no problem, i'm iterate on unmarshaled struct...

**Comment by s8sg** [comment]
If you come up with the code to construct flow with iteration can you raise a PR adding it in the `sdk. The similar can be used for AWS State language

**Comment by vtolstov** [comment]
Yes, I'm plan to do that.

ср, 21 авг. 2019 г., 11:03 Swarvanu Sengupta <notifications@github.com>:
