### ISSUE TITLE
pass own request id instead of generate

### ISSUE THREAD

**Issue by vtolstov** [s8sg/faas-flow#91]
```
[Request `bl512bnm4edtn6s1puj0`] Completed successfully
```

if i have already generated request id (uuid) how can i pass it to executor inside raw request?
my use-case - when user hits api gateway for all requests i generate request id and it used in all logs and tracing. Will be good to have it also in faas-flow too. So basing on this ID i can get all needed data to understand what user do and what he get.

**Comment by s8sg** [comment]
You can also map your requestId to a faasflow requestId and handle it inside executor

**Comment by s8sg** [comment]
This was asked for batch processing as well. Maybe we can support passing request ID

**Comment by vtolstov** [comment]
In case of passing RawRequest via NewRequest i can't pass own request id to map it in executor (or i need to encode it in Data []byte)

**Comment by s8sg** [comment]
No it's not supported now. I'm thinking it may be a good idea to support it.

**Comment by vtolstov** [comment]
Do you understand how to add this?

**Comment by s8sg** [comment]
Yeah the adding part is straight Forward. We may take the request as a input in a header/query. We already using one header, we may use another such as: ‘x-faasflow-reuse-id’
