### ISSUE TITLE
restart workflow or something like this

### ISSUE THREAD

**Issue by vtolstov** [s8sg/faas-flow#92]
for debug purpose i want to store all stuff in data store and state store to be able to restart workflow.
what is the best way to do that - get raw request from storage or... ?

**Comment by s8sg** [comment]
If you writing your own Executor you can do it pretty easily. All you need is to stop `Execute()` iteration and debug the intermediate result. 

In case of `faas-flow` Exector, once pause will be implemented one can use that feature. It will keep the `intermediate` result on stores.

**Comment by vtolstov** [comment]
As stop and other implemented, how can we do restart? Simply pass original input to workflow? Does it enought?

**Comment by s8sg** [comment]
passing an original input to workflow would work.

**Comment by s8sg** [comment]
For this we don't need any separate handling, can we close the same ?
