### ISSUE TITLE
Make faas-flow data encoder to be flexible, so one may use something else than json

### ISSUE THREAD

**Issue by vtolstov** [s8sg/faas-flow#93]
why state store gets base64 encoded data, i think that it must get raw data that encoded/decoded outside. I want to use google protobuf message so it in binary and not need to be converted to/from base64...

**Comment by chennqqi** [comment]
data store in `[]byte` slice. all openfaas return `[]byte` slice.
json.Marshal a `[]byte` slice default action is encoding to base64 string

**Comment by vtolstov** [comment]
i'm write own store for data and state and check it contents. data base64 encoded

**Comment by vtolstov** [comment]
```
// Set put a value in the context using DataStore                           
func (context *Context) Set(key string, data interface{}) error {           
  c := struct {                                                             
    Key   string      `json:"key"`                                          
    Value interface{} `json:"value"`                                        
  }{Key: key, Value: data}                                                  
  b, err := json.Marshal(&c)                                                
  if err != nil {                                                           
    return fmt.Errorf("Failed to marshal data, error %v", err)              
  }                                                                         
                                                                            
  return context.dataStore.Set(key, string(b))                              
}                                                                           
```

**Comment by vtolstov** [comment]
@s8sg as i think i need to create own context package to have ability to use raw bytes without encode/decode.

**Comment by s8sg** [comment]
I think the whole context might not be a interface, but suddenly the underlying data encoder can be. So at the time of context initialization executor initiate a default encoder. One may override it by there own. Encoder get called for Set() and Get() method

**Comment by vtolstov** [comment]
Yes, this will be good
