### ISSUE TITLE
Change context in SDK to Operate on []byte 

### ISSUE THREAD

**Issue by vtolstov** [s8sg/faas-flow#95]
i'm plan to modify context.go, firstly i want to modify Get and Set to return error and not panic,
also does we really need to have GetInt GetString and so?
I think that context must operate on []byte and hi-level app need to cast/decode needed stuff.

**Comment by chennqqi** [comment]
GetInt GetString are covinient for user writing dag flow

**Comment by s8sg** [comment]
sdk `Context` and `Faasflow Context` can be different. I agree. If you are changing the context to have `set()` and `get()` then we may not need the encoder as proposed in #93 in sdk.

If you raising a PR, please also add an `faasflow.Context` with `encoding` logic and the convenience method,  so that it the current faasflow code doesn't break

**Comment by s8sg** [comment]
@vtolstov have you made any progress on the same, otherwise I may take it

**Comment by vtolstov** [comment]
Ah sorry, you can take it. I'm try to deeply investigate sdk and create some code for rpc(to be able to construct workflow via rpc and store it in store)

**Comment by vtolstov** [comment]
@s8sg do you have some progress on sdk/context ?

**Comment by vtolstov** [comment]
also i think that we need to remove all panic from context.go and return ([]byte, error) from get func, and error from set func.

**Comment by s8sg** [comment]
I’ll complete it on this weekend.

**Comment by vtolstov** [comment]
fine

**Comment by vtolstov** [comment]
i think that this can be first #121 
so we change to []byte slice for data store. after that i'm add encoder logic and call Encode/Decode methods on it. But underlining data store operates on bytes.

**Comment by s8sg** [comment]
This has a PR open, please incorporate the review comments and get it merged.
