### ISSUE TITLE
ability to register own sdk.Operation to some map[string]sdk.Operation

### ISSUE THREAD

**Issue by vtolstov** [s8sg/faas-flow#98]
Do be able to construct Dag from json we need to have map[string]sdk.Operation
so when we have sdk.OperationExporter we can unmarshal json operation Properties to needed struct and assign this operation to node.

**Comment by vtolstov** [comment]
@s8sg can you provide some suggestions for function name or some interface definition for such stuff?

**Comment by vtolstov** [comment]
also for sdk.Operation we need some method to reconstruct it from Properties. Or what you think?

**Comment by vtolstov** [comment]
sorry for noise, also i think that sdk.Operation need Execute method, so faas-flow runs Execute method for each operation inside executor.ExecuteOperation method.
Because only sdk.Operation known how to execute it, this save type switch inside ExecuteOperation method. For example Execute method in sdk.Operation can be func Execute([]byte) ([]byte, error)

**Comment by s8sg** [comment]
Operation execution part is loosely coupled with Sdk while highly coupled with executor. Which means Executor defines what a operation is and what type of value it expect. So the Execute() function signature is not a concern of sdk. One may use the underlying type of sdk.Operation to implement a separate interface that define Execute(). By calling ExecuteOperation() sdk delegate the operation handling part to the executor. 

Now coming to the question how to reconstruct a operation from Properties. I guess one way is to have more generic method like Encode() on operation, along with the GetProperties(). But its still possible with GetProperties() alone

Now while constructing a new workflow from a definition, it can pass some new interface such as: OperationContructor. OperationConstructor provide Construct(properties map[string][]string) (*Operation, error). 

So one do.       
Err = flow.FromDefinition(definition, opsConstructor)

**Comment by vtolstov** [comment]
without delegating execution part to custom sdk.Operation we lost usability in case of adding new Operation. For example when i need to ad my own operation i need create go file for it wit needed struct that satisfies interface. After that i need to modify my executor to add support for this action.

When operation have some method like Call, executor can run this method and expect []byte, error returned values and not need to known about specific operation internals.

**Comment by s8sg** [comment]
Thats a valid point.

**Comment by vtolstov** [comment]
so do you suggest me to add to sdk.Operation method Call with provided signature? I can create pr =)

**Comment by s8sg** [comment]
I guess its better to Add an `Encode()`  
```go
type Operation interface {
	GetId() string
	GetProperties() map[string][]string

        Execute([]byte) ([]byte, error)
        Encode() (string, error)
}
``` 
It will need change in executor code, where we are calling `ExecuteOperation`. 
As well as in faasflow executor code.

**Comment by vtolstov** [comment]
Ah, ok so we add encode and execute. May i suggest return byte slice in encode and not string?
Also add decode from byte slice?

**Comment by s8sg** [comment]
This one is already implemented 
https://github.com/s8sg/faas-flow/blob/master/sdk/operation.go#L5

**Comment by vtolstov** [comment]
It lacks decode method to be able to construct operation from json
